src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=AnnoncesRepository::class)
 */
class Annonces
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @var \DateTime $created_at
     * 
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
    */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=Images::class, mappedBy="annonces", orphanRemoval=true, cascade={"persist"})
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = ucfirst($title);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }




    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }



    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAnnonces($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAnnonces() === $this) {
                $image->setAnnonces(null);
            }
        }

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity=Annonces::class, mappedBy="users", orphanRemoval=true)
     */
    private $annonces;

    public function __construct()
    {
        $this->annonces = new ArrayCollection();
    }

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Annonces[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonces $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setUsers($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getUsers() === $this) {
                $annonce->setUsers(null);
            }
        }

        return $this;
    }


}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Dompdf\Dompdf;
use Dompdf\Options;
use App\Repository\AnnoncesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class MainController extends AbstractController
{
    private  $annoncesRepo;

    public function __construct(AnnoncesRepository $annoncesRepo)
    {
        $this->annoncesRepo = $annoncesRepo;
    }

    /**
     * @Route("/", name="app_home")
     */
    public function index( Request $request)
    {
        
        $limit = 10;
        $page = (int)$request->query->get("page", 1);
        $annonces = $this->annoncesRepo->getPaginatedAnnonces($page, $limit);
        $total = $this->annoncesRepo->getTotalAnnonces();

        if (!$annonces) {
            throw new NotFoundHttpException('Aucunes annonces trouvée');
        }

        return $this->render('main/index.html.twig', compact('annonces', 'total', 'limit', 'page'));
    }

    /**
     * @Route("/details/{slug}", name="annonces_details")
     */
    public function details($slug)
    {
        $annonce = $this->annoncesRepo->findOneBy(['slug' => $slug]);

        if (!$annonce) {
            throw new NotFoundHttpException('Pas d\'annonce trouvée');
        }



        return $this->render('main/details.html.twig', [
            'annonce' => $annonce,
        ]);
    }

    /**
     * @Route("/download/{slug}", name="annonces_download")
     */
    public function download($slug)
    {
        $annonce = $this->annoncesRepo->findOneBy(['slug' => $slug]);

        if (!$annonce) {
            throw new NotFoundHttpException('Pas d\'annonce trouvée');
        }

               // On définit les options du PDF
               $pdfOptions = new Options();
               // Police par défaut
               $pdfOptions->set('defaultFont', 'Arial');
               $pdfOptions->setIsRemoteEnabled(true);
       
               // On instancie Dompdf
               $dompdf = new Dompdf($pdfOptions);
               $context = stream_context_create([
                   'ssl' => [
                       'verify_peer' => FALSE,
                       'verify_peer_name' => FALSE,
                       'allow_self_signed' => TRUE
                   ]
               ]);
               $dompdf->setHttpContext($context);
       
               // On génère le html
               $html = $this->renderView('main/download.html.twig', [
                'annonce' => $annonce,
            ]);
       
               $dompdf->loadHtml($html);
               $dompdf->setPaper('A4', 'portrait');
               $dompdf->render();
        // On génère un nom de fichier
        $fichier = 'annonce-' . $slug .'.pdf';

        // On envoie le PDF au navigateur
        $dompdf->stream($fichier, [
            'Attachment' => true
        ]);               return new Response();
    }
}

templates/main/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{annonce.title}}
{% endblock %}
{% block stylesheets %}{% endblock %}
{% block body %}
	<div class="container mt-5 mb-5">
		<div class="row">
			<div class="col-md-8">
			{# Début carousel #}
		<div id="carouselExampleIndicators" style="max-width: 700px;" class="carousel slide" data-ride="carousel">
			{# fleches #}
			<ol class="carousel-indicators">
				{% for image in annonce.images %}
					{% if loop.first %}
						{% set active = 'active' %}
					{% else %}
						{% set active = " " %}
					{% endif %}
					<li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" class="{{ active }}"></li>
				{% endfor %}
			</ol>
			{# Images pour le carousel #}
			<div class="carousel-inner">
				{% for image in annonce.images %}
					{% if loop.first %}
						{% set active = 'active' %}
					{% else %}
						{% set active = " " %}
					{% endif %}
					<div class="carousel-item {{ active }}">
					<img  src="{{ asset('uploads/images/annonces/' ~ image.name)|imagine_filter('banniere') }}" class="d-block w-100" alt="{{ annonce.title }}">
					</div>
					{% else %}
					<img src="{{ asset('uploads/images/no-photo.png')|imagine_filter('banniere') }}" class="card-img" alt="{{ annonce.title }}">
				{% endfor %}
			</div>
			{# Chevron #}
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
		{# Fin carousel #}			</div>
			<div class="col-md-4">
				<div class="card text-center">
					<div class="row no-gutters">
						<div class="col-md-4">
							<img src="{{ asset('img/user.png') }}" style="max-width: 100px;" class="card-img" alt="{{ annonce.title }}">
						</div>
						<div class="col-md-8">
							<div class="card-body">
								<h5 class="card-title">
									{{annonce.users.firstname}}
								</h5>
							</div>
						</div>
						<div class="card-body">
							<div class="container" style="margin-top: 50px;">
								<p>{{ annonce.users.username}}</p>
								<p>{{ annonce.users.phone}}</p>
							</div>
						</div>
					</div> 
				</div>
			</div>
		</div>
		<div class="card mb-3 mt-4 align-center" style="max-width: 1200px;">
			<div class="row no-gutters">
				<div class="col-md-4 my-auto">
					<img  src="{{ asset('img/logo.png') }}" style="max-width: 150px; margin-left: 7em;" class="img-responsive d-block" alt="{{ annonce.title }}">
				</div>
				<div class="col-md-8">
					<div class="card-body">
						<h5 class="card-title">
							{{ annonce.title }}
						</h5>
						<p class="card-text">
							<strong>{{ annonce.price }}</strong> €
						</p>
						<p class="card-text">{{ annonce.content|raw }}</p>
						<p class="card-text">
							<small class="text-muted">Publié le
								{{annonce.createdAt | date ('d/m/Y à H:i')}}
							</small>
						</p>
					</div>
				</div>
			</div>
		</div>
		<a href="{{ path('annonces_download', {slug: annonce.slug}) }}" class="btn btn-secondary">Téléchrger en PDF</a>
	</div>
</div>
{% endblock %}
{% block javascripts %}{% endblock %}

templates/main/download.html.twig
{% extends "base-pdf.html.twig" %}
{% block title %}{{annonce.title}}{% endblock %}
{% block body %}
    <h1 style="text-align: center;">{{annonce.title}}</h1>
    <br><br>
        <h2 style="text-align: center;">Coordonées de l'annonceur</h2>
        <br>
    <table style="width: 100%;" border=1>
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">E-mail</th>
                <th scope="col">Téléphone</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{annonce.users.firstname}}</td>
                <td>{{ annonce.users.username}}</td>
                <td>{{ annonce.users.phone}}</td>
            </tr>
        </tbody>
    </table>
    <br><br>
    <h2 style="text-align: center;">Photo(s) de l'annonce</h2>
    <br>
    {% for image in annonce.images %}
                <img style="width: 200px;" src="{{ asset('uploads/images/annonces/' ~ image.name)|imagine_filter('banniere') }}"  alt="{{ annonce.title }}">
			{% else %}
				<img style="width: 200px;" src="{{ asset('uploads/images/no-photo.png')|imagine_filter('banniere') }}"  alt="{{ annonce.title }}"> 
    {% endfor %}
    <br><br>
    <h2 style="text-align: center;">Détail de l'annonce</h2>
		<div >
			<p style="text-align: center;">
				<strong>{{ annonce.price }}</strong> €
			</p>
			<p>{{ annonce.content|raw }}</p>
			<p >
				<small class="text-muted">Publié le
					{{annonce.createdAt | date ('d/m/Y à H:i')}}
				</small>
			</p>
		</div>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Petites Annonces{% endblock %}

{% block body %}
<div class="container py-4">
    {% for message in app.flashes('success') %}
        <div class="mt-4 alert alert-success alert-dismissible fade show" role="alert">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button> 
        </div>
    {% endfor %}
    	<div class="container">
        <div class="row">
			{% for annonce in annonces %}
            <div class="col-6">
				<div class="card mb-3 mt-4 align-center" style="max-width: 700px;">
					<div class="row no-gutters">
						<div class="col-md-4 ">
						{% for image in annonce.images %}
								{% if loop.first %}
									<img src="{{ asset('uploads/images/annonces/' ~ image.name)|imagine_filter('square') }}" class="card-img" alt="{{ annonce.title }}">
								{% endif %}
									{% else %}
									<img src="{{ asset('uploads/images/no-photo.png')|imagine_filter('square') }}" class="card-img" alt="{{ annonce.title }}">
						{% endfor %}
						</div>
						<div class="col-md-8">
							<div class="card-body">
								<h5 class="card-title">
									<a href="{{ path('annonces_details', {slug: annonce.slug}) }}">{{ annonce.title }}</a>
								</h5>
								<p class="card-text">Catégorie :
									<small>{{ annonce.categories.name }}</small>
								</p>
								<p class="card-text">{{ annonce.price}} €</p>
								<p class="card-text">
									<small class="text-muted">Publié le
										{{annonce.createdAt | date ('d/m/Y à H:i')}}
										par
										<strong>{{annonce.users.firstname}}</strong>
									</small>
								</p>
						</div>
					</div>
				</div>
		    </div>
        </div>
		{% endfor %}
        </div>
</div>
		<div class="container">
			<div class="row justify-content-center">
			<nav aria-label="...">
				<ul class="pagination">
					<li class="{{ (page == 1) ? 'page-item disabled' : '' }}">
						<a class="page-link" href="?page=1">
							<i class="fas fa-step-backward"></i>
						</a>
					</li>    
					<li class="{{ (page == 1) ? 'page-item disabled' : '' }}">
						<a class="page-link" href="{{ (page > 1) ? '?page=' ~ (page - 1) : '' }}">
							<i class="fas fa-angle-left"></i>
						</a>
					</li>
					{% set pages = (total / limit)|round(0, 'ceil') %}
					{% for item in 1..pages %}
						<li class="{{ (page == item) ? 'page-item active' : '' }}">
							<a class="page-link" href="?page={{ item }}">{{ item }}</a>
						</li>
					{% endfor %}
					<li class="{{ (page == pages) ? 'page-item disabled' : '' }}">
						<a class="page-link" href="{{ (page < pages) ? '?page=' ~ (page + 1) : '' }}">
							<i class="fas fa-angle-right"></i>
						</a>
					</li>
					<li class="{{ (page == pages) ? 'page-item disabled' : '' }}">
						<a class="page-link" href="?page={{ pages }}">
							<i class="fas fa-step-forward"></i>
						</a>
					</li>
				</ul>		
			</nav>
		</div>
	</div>
{% endblock %}